---
language: perl
perl:
  - '5.24'
  - '5.22'
  - '5.20'
sudo: false
before_install:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
after_success:
  - cover -test -report coveralls
notifications:
  email: false
